version: '3'

tasks:
  build:
    cmds:
      - go build -v -o backuper.exe ./cmd/backuper/
  run:
    cmds:
      - go build -v -o backuper.exe ./cmd/backuper/
      - ./backuper.exe --selfaddr $TFTP
  test:
    cmds:
      - go build -v -o backuper.exe ./cmd/backuper/
      - ./backuper.exe --selfaddr $TFTP --test
